apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  labels:
    app: {{ .Values.pod.labels.app }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.pod.labels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.pod.labels.app }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        {{- range .Values.pod.containers }}
        - name: {{ .name }}
          image: {{ .image }}
          imagePullPolicy: {{ .imagePullPolicy }}
          ports:
            {{- range .ports }}
            - containerPort: {{ .containerPort }}
            {{- end }}
          {{- if .volumeMounts }}
          volumeMounts:
            {{- range .volumeMounts }}
            - mountPath: {{ .mountPath }}
              name: {{ .name }}
            {{- end }}
          {{- end }}
        {{- end }}
      volumes:
        {{- range .Values.pod.volumes }}
        - name: {{ .name }}
          hostPath:
            path: {{ .hostPath.path }}
        {{- end }}
